#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
  formatter: json
# File Options
files:
  include: 'scout-files/_sass/*.s+(a|c)ss'
# Rule Configuration
rules:
  attribute-quotes: 2
  brace-style:
    - 2
    - allow-single-line: false
    - style: '1tbs'
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq
  no-color-keywords: 1
  no-debug: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-important: 2
  no-invalid-hex: 1
  no-mergeable-selectors: 2
  no-misspelled-properties: 1
  no-qualifying-elements:
   - 2
   - allow-element-with-attribute: true
   - allow-element-with-class: false
   - allow-element-with-id: false
  no-trailing-whitespace: 1
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    - ignore-custom-properties: true
      order:
        - content

        - position
        - top
        - right
        - bottom
        - left

        - display
        - align-content
        - align-items
        - align-self
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - justify-content
        - order

        - width
        - height
        - min-width
        - min-height
        - max-width
        - max-height

        - background
        - background-color
        - background-image
        - background-position
        - background-repeat
        - background-size

        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left

        - color
        - font-family
        - font-size
        - -webkit-font-smoothing
        - font-smoothing
        - font-style
        - font-weight
        - font-variant
        - letter-spacing
        - line-height
        - list-style
        - list-style-image
        - list-style-position
        - list-style-type
        - speak
        - text-align
        - text-decoration
        - text-overflow
        - text-rendering
        - text-shadow
        - text-transform
        - white-space
        - word-break

        - box-shadow
        - clear
        - cursor
        - float
        - opacity
        - outline
        - outline-offset
        - overflow
        - perspective
        - pointer-events
        - -webkit-transform
        - transform
        - -webkit-transition
        - transition
        - vertical-align
        - visibility
        - z-index
  single-line-per-selector: 1
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-around-operator:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon:
    - 1
    - include: false
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon:
    - 1
    - include: true
  url-quotes: 1
  zero-unit:
    - 1
    - include: true
